apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-web
  namespace: devops-portfolio
spec:
  type: ClusterIP
  selector:
    app: devops-portfolio-web
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http